### ISSUE TITLE
pathfinder orchestration: make CLI more user-friendly

### ISSUE THREAD

**Issue by nefanov** [nefanov/pathfinder#11]
1) Add -o option to frontends: optionally saving of dot graph permanently
2) I wondered that when I pass 1.c as -file argument, frontend can't find it . Fix please.
3) (related to 2). Frontend always print out "copy it and run dot -Tpng...". Omit this if failed.
4) Think about more user-friendly CLI, configuration files, cmd line options, etc.

**Comment by pr0kuk** [comment]
>  I wondered that when I pass 1.c as -file argument, frontend can't find it . Fix please.
>  Think about more user-friendly CLI, configuration files, cmd line options, etc.

We have three types of input:
1) All through stdin
2) .c filename through CLI
3) full file input

So now to use the 2) option we use `-cmd` flag and to use the 3) option we use `-file` flag.
It can cause a misunderstanding, because in the 2) variant you need to specify the source .c file but in the 3) var. you need to specify special input file (examples of such files you can see in `gcc-cfg-utils/input`)

Therefore the question is what are the best flags to use for these options, or how can I modify it?
